apiVersion: v1
kind: Service
metadata:
  name: mergesort-server
  labels:
    app: mergesort-server
spec:
  type: NodePort
  selector:
    app: mergesort-server
  ports:
  - port: 12345
    targetPort: 12345
    nodePort: 30345
    protocol: TCP
    name: tcp
